version: '3'

services:
  nginx:
    container_name: app-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/app:delegated
      - ./etc/infrastructure/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    container_name: app-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
    - .:/app:delegated
    env_file:
      - .env