version: '3'

services:
  nginx:
    container_name: app-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/app:delegated
      - ./etc/infrastructure/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    container_name: app-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
    - .:/app:delegated
    env_file:
      - .env

  mysql:
    container_name: app-mysql
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db-volume:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

volumes:
  db-volume: