version: '3'

services:
  nginx:
    container_name: app-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/app:delegated
    depends_on:
      - php

  php:
    container_name: app-php
    build:
      context: ./docker/php
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    ports:
    - "9001:9001"
    volumes:
    - .:/app:delegated
    env_file:
      - .env